# ============================================================================
# Shiny Application: Comprehensive Data Analysis Dashboard
# Description: Interactive dashboard showcasing iris and mtcars analyses
# Usage: R -e "shiny::runApp('app.R')"
# ============================================================================

library(shiny)
library(tidyverse)
library(plotly)
library(DT)
library(bslib)

# Load data -------------------------------------------------------------------
iris_df <- read_csv("data/raw/iris.csv", show_col_types = FALSE)
mtcars_df <- read_csv("data/raw/mtcars.csv", show_col_types = FALSE)

# Load statistical results if available
stats_results <- tryCatch(
 readRDS("output/statistical_results.rds"),
 error = function(e) NULL
)

# Modern color palette (colorblind-safe) --------------------------------------
species_colors <- c(
 "setosa" = "#332288",
 "versicolor" = "#44AA99",
 "virginica" = "#CC6677"
)

cyl_colors <- c(
 "4" = "#117733",
 "6" = "#DDCC77",
 "8" = "#CC6677"
)

# ============================================================================
# UI
# ============================================================================

ui <- page_navbar(
 title = "Data Analysis Dashboard",
 theme = bs_theme(
   version = 5,
   bootswatch = "flatly",
   primary = "#2c3e50",
   "navbar-bg" = "#2c3e50"
 ),

 # --- Gallery Tab ---
 nav_panel(
   title = "Visualization Gallery",
   icon = icon("images"),

   layout_columns(
     col_widths = c(12),

     card(
       card_header(
         class = "bg-primary text-white",
         "Publication-Quality Visualizations"
       ),
       card_body(
         p("High-quality static visualizations generated by specialized R agents."),

         layout_columns(
           col_widths = c(6, 6),

           card(
             card_header("Iris: Petal Morphology"),
             card_body(
               if (file.exists("output/iris_publication_viz.png")) {
                 tags$img(
                   src = "iris_publication_viz.png",
                   style = "width: 100%; border-radius: 8px; box-shadow: 0 4px 6px rgba(0,0,0,0.1);"
                 )
               } else {
                 p("Visualization not yet generated. Run scripts/03_iris_publication_viz.R")
               }
             )
           ),

           card(
             card_header("Iris: Sepal Morphology"),
             card_body(
               if (file.exists("output/iris_sepal_viz.png")) {
                 tags$img(
                   src = "iris_sepal_viz.png",
                   style = "width: 100%; border-radius: 8px; box-shadow: 0 4px 6px rgba(0,0,0,0.1);"
                 )
               } else {
                 p("Visualization not yet generated.")
               }
             )
           )
         ),

         br(),

         layout_columns(
           col_widths = c(12),

           card(
             card_header("MTCars: Performance Analysis"),
             card_body(
               if (file.exists("output/mtcars_publication_viz.png")) {
                 tags$img(
                   src = "mtcars_publication_viz.png",
                   style = "width: 100%; max-width: 900px; margin: 0 auto; display: block; border-radius: 8px; box-shadow: 0 4px 6px rgba(0,0,0,0.1);"
                 )
               } else {
                 p("Visualization not yet generated. Run scripts/04_mtcars_publication_viz.R")
               }
             )
           )
         )
       )
     )
   )
 ),

 # --- Interactive Exploration Tab ---
 nav_panel(
   title = "Interactive Explorer",
   icon = icon("chart-scatter"),

   layout_sidebar(
     sidebar = sidebar(
       width = 280,

       selectInput(
         "dataset",
         "Select Dataset:",
         choices = c("Iris" = "iris", "MTCars" = "mtcars")
       ),

       hr(),

       conditionalPanel(
         condition = "input.dataset == 'iris'",
         selectInput(
           "iris_x",
           "X Variable:",
           choices = c("Sepal.Length", "Sepal.Width", "Petal.Length", "Petal.Width"),
           selected = "Petal.Length"
         ),
         selectInput(
           "iris_y",
           "Y Variable:",
           choices = c("Sepal.Length", "Sepal.Width", "Petal.Length", "Petal.Width"),
           selected = "Petal.Width"
         ),
         checkboxGroupInput(
           "iris_species",
           "Species:",
           choices = unique(iris_df$Species),
           selected = unique(iris_df$Species)
         )
       ),

       conditionalPanel(
         condition = "input.dataset == 'mtcars'",
         selectInput(
           "mtcars_x",
           "X Variable:",
           choices = c("mpg", "cyl", "disp", "hp", "wt", "qsec"),
           selected = "hp"
         ),
         selectInput(
           "mtcars_y",
           "Y Variable:",
           choices = c("mpg", "cyl", "disp", "hp", "wt", "qsec"),
           selected = "mpg"
         ),
         checkboxGroupInput(
           "mtcars_cyl",
           "Cylinders:",
           choices = sort(unique(mtcars_df$cyl)),
           selected = sort(unique(mtcars_df$cyl))
         )
       )
     ),

     layout_columns(
       col_widths = c(12),

       card(
         card_header("Interactive Scatter Plot"),
         card_body(
           plotlyOutput("scatter_plot", height = "500px")
         )
       )
     ),

     layout_columns(
       col_widths = c(12),

       card(
         card_header("Data Table"),
         card_body(
           DTOutput("data_table")
         )
       )
     )
   )
 ),

 # --- Statistical Analysis Tab ---
 nav_panel(
   title = "Statistical Analysis",
   icon = icon("calculator"),

   layout_columns(
     col_widths = c(6, 6),

     # Iris Statistics
     card(
       card_header(
         class = "bg-info text-white",
         "Iris Dataset Analysis"
       ),
       card_body(
         h5("Descriptive Statistics by Species"),
         tableOutput("iris_desc_stats"),

         hr(),

         h5("ANOVA: Petal Length ~ Species"),
         verbatimTextOutput("iris_anova"),

         hr(),

         h5("Tukey HSD Post-hoc Comparisons"),
         verbatimTextOutput("iris_tukey")
       )
     ),

     # MTCars Statistics
     card(
       card_header(
         class = "bg-success text-white",
         "MTCars Dataset Analysis"
       ),
       card_body(
         h5("Correlation Matrix"),
         plotlyOutput("mtcars_corr_plot", height = "300px"),

         hr(),

         h5("Linear Regression: MPG ~ HP + Weight"),
         verbatimTextOutput("mtcars_regression"),

         hr(),

         h5("Model Summary"),
         tableOutput("mtcars_model_summary")
       )
     )
   )
 ),

 # --- Summary Tab ---
 nav_panel(
   title = "Summary",
   icon = icon("chart-pie"),

   layout_columns(
     col_widths = c(4, 4, 4),

     value_box(
       title = "Iris Samples",
       value = nrow(iris_df),
       showcase = icon("leaf"),
       theme = "primary"
     ),

     value_box(
       title = "MTCars Vehicles",
       value = nrow(mtcars_df),
       showcase = icon("car"),
       theme = "success"
     ),

     value_box(
       title = "Visualizations",
       value = length(list.files("output", pattern = "\\.png$")),
       showcase = icon("image"),
       theme = "info"
     )
   ),

   layout_columns(
     col_widths = c(6, 6),

     card(
       card_header("Iris Species Distribution"),
       card_body(
         plotlyOutput("iris_pie", height = "350px")
       )
     ),

     card(
       card_header("MTCars Cylinder Distribution"),
       card_body(
         plotlyOutput("mtcars_bar", height = "350px")
       )
     )
   )
 )
)

# ============================================================================
# Server
# ============================================================================

server <- function(input, output, session) {

 # Reactive: Get filtered data
 filtered_data <- reactive({
   if (input$dataset == "iris") {
     iris_df |>
       filter(Species %in% input$iris_species)
   } else {
     mtcars_df |>
       filter(cyl %in% input$mtcars_cyl)
   }
 })

 # Output: Interactive scatter plot
 output$scatter_plot <- renderPlotly({
   df <- filtered_data()

   if (input$dataset == "iris") {
     p <- ggplot(df, aes(
       x = .data[[input$iris_x]],
       y = .data[[input$iris_y]],
       color = Species,
       text = paste("Species:", Species)
     )) +
       geom_point(size = 3, alpha = 0.7) +
       stat_ellipse(level = 0.95, linetype = "dashed") +
       theme_minimal(base_size = 14) +
       scale_color_manual(values = species_colors) +
       labs(
         title = paste("Iris:", input$iris_x, "vs", input$iris_y),
         x = input$iris_x,
         y = input$iris_y
       )
   } else {
     p <- ggplot(df, aes(
       x = .data[[input$mtcars_x]],
       y = .data[[input$mtcars_y]],
       color = factor(cyl),
       text = paste("Car:", rownames(df))
     )) +
       geom_point(size = 3, alpha = 0.7) +
       geom_smooth(method = "lm", se = TRUE, alpha = 0.2) +
       theme_minimal(base_size = 14) +
       scale_color_manual(values = cyl_colors) +
       labs(
         title = paste("MTCars:", input$mtcars_x, "vs", input$mtcars_y),
         x = input$mtcars_x,
         y = input$mtcars_y,
         color = "Cylinders"
       )
   }

   ggplotly(p, tooltip = "text") |>
     layout(legend = list(orientation = "h", y = -0.15))
 })

 # Output: Data table
 output$data_table <- renderDT({
   datatable(
     filtered_data(),
     options = list(
       pageLength = 10,
       scrollX = TRUE,
       dom = 'Bfrtip'
     ),
     class = "compact stripe hover"
   )
 })

 # Output: Iris descriptive statistics
 output$iris_desc_stats <- renderTable({
   iris_df |>
     group_by(Species) |>
     summarise(
       n = n(),
       `Petal.Length (mean)` = round(mean(Petal.Length), 2),
       `Petal.Width (mean)` = round(mean(Petal.Width), 2),
       `Sepal.Length (mean)` = round(mean(Sepal.Length), 2),
       `Sepal.Width (mean)` = round(mean(Sepal.Width), 2),
       .groups = "drop"
     )
 }, striped = TRUE, hover = TRUE)

 # Output: Iris ANOVA
 output$iris_anova <- renderPrint({
   model <- aov(Petal.Length ~ Species, data = iris_df)
   summary(model)
 })

 # Output: Iris Tukey
 output$iris_tukey <- renderPrint({
   model <- aov(Petal.Length ~ Species, data = iris_df)
   TukeyHSD(model)
 })

 # Output: MTCars correlation plot
 output$mtcars_corr_plot <- renderPlotly({
   cor_vars <- c("mpg", "hp", "wt", "disp")
   cor_matrix <- cor(mtcars_df[, cor_vars], use = "complete.obs")

   plot_ly(
     x = cor_vars,
     y = cor_vars,
     z = cor_matrix,
     type = "heatmap",
     colors = colorRamp(c("#CC6677", "#FFFFFF", "#117733")),
     zmin = -1, zmax = 1
   ) |>
     layout(
       xaxis = list(title = ""),
       yaxis = list(title = "")
     )
 })

 # Output: MTCars regression
 output$mtcars_regression <- renderPrint({
   model <- lm(mpg ~ hp + wt, data = mtcars_df)
   summary(model)
 })

 # Output: MTCars model summary table
 output$mtcars_model_summary <- renderTable({
   model <- lm(mpg ~ hp + wt, data = mtcars_df)
   data.frame(
     Metric = c("R-squared", "Adj. R-squared", "F-statistic", "p-value"),
     Value = c(
       round(summary(model)$r.squared, 4),
       round(summary(model)$adj.r.squared, 4),
       round(summary(model)$fstatistic[1], 2),
       format.pval(pf(
         summary(model)$fstatistic[1],
         summary(model)$fstatistic[2],
         summary(model)$fstatistic[3],
         lower.tail = FALSE
       ), digits = 3)
     )
   )
 }, striped = TRUE)

 # Output: Iris pie chart
 output$iris_pie <- renderPlotly({
   counts <- iris_df |>
     count(Species)

   plot_ly(
     counts,
     labels = ~Species,
     values = ~n,
     type = "pie",
     marker = list(colors = unname(species_colors)),
     textinfo = "label+percent"
   ) |>
     layout(showlegend = FALSE)
 })

 # Output: MTCars bar chart
 output$mtcars_bar <- renderPlotly({
   counts <- mtcars_df |>
     count(cyl) |>
     mutate(cyl = factor(cyl))

   plot_ly(
     counts,
     x = ~cyl,
     y = ~n,
     type = "bar",
     marker = list(color = unname(cyl_colors))
   ) |>
     layout(
       xaxis = list(title = "Cylinders"),
       yaxis = list(title = "Count")
     )
 })
}

# ============================================================================
# Run Application
# ============================================================================

shinyApp(ui = ui, server = server)
